 const WORD_CATEGORIES = {
            // 🌍 Rund um die Welt
            travel: [
                { word: "Eiffelturm", hint: "Paris" },
                { word: "Big Ben", hint: "London" },
                { word: "Kolosseum", hint: "Rom" },
                { word: "Pyramiden", hint: "Ägypten" },
                { word: "Taj Mahal", hint: "Indien" },
                { word: "Machu Picchu", hint: "Peru" },
                { word: "Neuschwanstein", hint: "Bayern" },
                { word: "Sagrada Familia", hint: "Barcelona" },
                { word: "Mount Rushmore", hint: "Amerika" },
                { word: "Brandenburger Tor", hint: "Berlin" },
                { word: "Statue of Liberty", hint: "New York" },
                { word: "Stonehenge", hint: "England" },
                { word: "Gondel", hint: "Venedig" },
                { word: "Safari", hint: "Afrika" },
                { word: "Sushi", hint: "Japan" },
                { word: "Oktoberfest", hint: "München" },
                { word: "Tulpen", hint: "Holland" },
                { word: "Tango", hint: "Argentinien" },
                { word: "Backpacking", hint: "Reisen" },
                { word: "Flughafen", hint: "Terminal" }
            ],

            // 🎬 Unterhaltung
            entertainment: [
                { word: "Netflix", hint: "Streaming" },
                { word: "Popcorn", hint: "Kino" },
                { word: "Blockbuster", hint: "Erfolg" },
                { word: "Oscar", hint: "Preis" },
                { word: "Cliffhanger", hint: "Spannung" },
                { word: "Soundtrack", hint: "Musik" },
                { word: "Plot Twist", hint: "Wendung" },
                { word: "Spoiler", hint: "Verrat" },
                { word: "Binge-watching", hint: "Marathon" },
                { word: "Red Carpet", hint: "Premiere" },
                { word: "Standing Ovation", hint: "Applaus" },
                { word: "Box Office", hint: "Kasse" },
                { word: "Behind the Scenes", hint: "Kulissen" },
                { word: "Director's Cut", hint: "Version" },
                { word: "Cameo", hint: "Auftritt" },
                { word: "Easter Egg", hint: "Versteckt" },
                { word: "Trailer", hint: "Vorschau" },
                { word: "Sequel", hint: "Fortsetzung" },
                { word: "Remake", hint: "Neuauflage" },
                { word: "Premiere", hint: "Erstaufführung" }
            ],

            // 🏠 Alltag  
            everyday: [
                { word: "Morgenmuffel", hint: "Müde" },
                { word: "Kaffeesucht", hint: "Abhängig" },
                { word: "Wecker", hint: "Aufstehen" },
                { word: "Pendeln", hint: "Arbeitsweg" },
                { word: "Feierabend", hint: "Entspannung" },
                { word: "Hausputz", hint: "Sauber" },
                { word: "Einkaufsliste", hint: "Vergessen" },
                { word: "Stau", hint: "Warten" },
                { word: "Parkplatzsuche", hint: "Stress" },
                { word: "WG-Leben", hint: "Teilen" },
                { word: "Abwasch", hint: "Spülen" },
                { word: "Nachbar", hint: "Nebenan" },
                { word: "Paketbote", hint: "Lieferung" },
                { word: "Warteschlange", hint: "Geduld" },
                { word: "Hausschlüssel", hint: "Vergessen" },
                { word: "Mülltonnen", hint: "Rausräumen" },
                { word: "Mittagspause", hint: "Erholung" },
                { word: "Wäsche", hint: "Waschen" },
                { word: "Supermarkt", hint: "Einkaufen" },
                { word: "Mitbewohner", hint: "Zusammenleben" }
            ],

            // 🐾 Tiere & Natur
            animals: [
                { word: "Flamingo", hint: "Rosa" },
                { word: "Pinguin", hint: "Watschelt" },
                { word: "Koala", hint: "Australisch" },
                { word: "Giraffe", hint: "Hals" },
                { word: "Delfin", hint: "Intelligent" },
                { word: "Faultier", hint: "Langsam" },
                { word: "Chamäleon", hint: "Wechselt" },
                { word: "Känguru", hint: "Hüpft" },
                { word: "Oktopus", hint: "Acht" },
                { word: "Seepferdchen", hint: "Maritim" },
                { word: "Erdmännchen", hint: "Wacht" },
                { word: "Alpaka", hint: "Flauschig" },
                { word: "Elefant", hint: "Rüssel" },
                { word: "Tiger", hint: "Gestreift" },
                { word: "Eule", hint: "Nachts" },
                { word: "Kolibri", hint: "Winzig" },
                { word: "Regenwurm", hint: "Boden" },
                { word: "Spinne", hint: "Netz" },
                { word: "Biene", hint: "Honig" },
                { word: "Schmetterling", hint: "Verwandlung" },
                { word: "Igel", hint: "Stachelig" },
                { word: "Eichhörnchen", hint: "Nüsse" },
                { word: "Waschbär", hint: "Maskiert" },
                { word: "Biber", hint: "Damm" },
                { word: "Lama", hint: "Spuckt" }
            ],

            // ⚽ Sport & Freizeit
            sports: [
                { word: "Overtime", hint: "Verlängerung" },
                { word: "Fair Play", hint: "Anstand" },
                { word: "Weltrekord", hint: "Bestzeit" },
                { word: "Mannschaftssport", hint: "Gemeinsam" },
                { word: "Einzelkämpfer", hint: "Solo" },
                { word: "Heimvorteil", hint: "Zuhause" },
                { word: "Underdog", hint: "Außenseiter" },
                { word: "Derby", hint: "Rivalität" },
                { word: "Playoffs", hint: "Entscheidung" },
                { word: "Meisterschaft", hint: "Titel" },
                { word: "Olympia", hint: "Ringe" },
                { word: "Doping", hint: "Betrug" },
                { word: "Schiedsrichter", hint: "Pfeife" },
                { word: "Fangesang", hint: "Supporters" },
                { word: "Vereinswechsel", hint: "Transfer" },
                { word: "Verletzungspause", hint: "Auszeit" },
                { word: "Comeback", hint: "Rückkehr" },
                { word: "Rookie", hint: "Neuling" },
                { word: "Veteran", hint: "Erfahren" },
                { word: "Sportgeist", hint: "Fairness" }
            ],

            // 📚 Wissen & Schule
            education: [
                { word: "Klassenarbeit", hint: "Stress" },
                { word: "Pausenhof", hint: "Pause" },
                { word: "Schulbrot", hint: "Verpflegung" },
                { word: "Hausaufgaben", hint: "Vergessen" },
                { word: "Lehrbuch", hint: "Schwer" },
                { word: "Schulranzen", hint: "Rücken" },
                { word: "Klassenkamerad", hint: "Freund" },
                { word: "Vertretungslehrer", hint: "Überraschung" },
                { word: "Zeugnis", hint: "Noten" },
                { word: "Abitur", hint: "Abschluss" },
                { word: "Studienbeginn", hint: "Universität" },
                { word: "Vorlesung", hint: "Hören" },
                { word: "Klausur", hint: "Prüfung" },
                { word: "Semester", hint: "Halbjahr" },
                { word: "Bachelor", hint: "Abschluss" },
                { word: "Praktikum", hint: "Erfahrung" },
                { word: "Bibliothek", hint: "Bücher" },
                { word: "Mensaessen", hint: "Günstig" },
                { word: "Campus", hint: "Gelände" },
                { word: "Diplomarbeit", hint: "Thesis" }
            ],

            // 🎉 Feste & Feiern
            celebrations: [
                { word: "Geburtstagstorte", hint: "Kerzen" },
                { word: "Konfetti", hint: "Bunt" },
                { word: "Überraschungsparty", hint: "Geheim" },
                { word: "Silvesterfeuer", hint: "Neujahr" },
                { word: "Weihnachtsmarkt", hint: "Glühwein" },
                { word: "Ostereiersuche", hint: "Versteckt" },
                { word: "Karnevalsumzug", hint: "Kostüme" },
                { word: "Hochzeitstorte", hint: "Süß" },
                { word: "Jubiläum", hint: "Jahrestag" },
                { word: "Familientreffen", hint: "Verwandtschaft" },
                { word: "Schulabschluss", hint: "Zeugnis" },
                { word: "Einschulung", hint: "Schultüte" },
                { word: "Junggesellenabschied", hint: "Letztes Mal" },
                { word: "Taufe", hint: "Wasser" },
                { word: "Kommunion", hint: "Kirche" },
                { word: "Firmenfeier", hint: "Kollegen" },
                { word: "Abschlussball", hint: "Elegant" },
                { word: "Gartenparty", hint: "Draußen" },
                { word: "Grillabend", hint: "Würstchen" },
                { word: "Geburtstagsständchen", hint: "Singen" }
            ],

            // 🇩🇪 Deutsche Begriffe
            german: [
                { word: "Verschlimmbessern", hint: "Schlimmer" },
                { word: "Fernweh", hint: "Sehnsucht" },
                { word: "Gemütlichkeit", hint: "Wohlfühlen" },
                { word: "Schadenfreude", hint: "Bosheit" },
                { word: "Wanderlust", hint: "Reisen" },
                { word: "Zeitgeist", hint: "Epoche" },
                { word: "Doppelgänger", hint: "Zwilling" },
                { word: "Kindergarten", hint: "Spielen" },
                { word: "Gesundheit", hint: "Niesen" },
                { word: "Weltschmerz", hint: "Traurigkeit" },
                { word: "Fingerspitzengefühl", hint: "Feinfühlig" },
                { word: "Ohrwurm", hint: "Melodie" },
                { word: "Kopfkino", hint: "Vorstellung" },
                { word: "Fremdschämen", hint: "Peinlich" },
                { word: "Verschlimmbessern", hint: "Kaputt" },
                { word: "Erklärungsnot", hint: "Rechtfertigung" },
                { word: "Stehaufmännchen", hint: "Widerstand" },
                { word: "Backpfeifengesicht", hint: "Unsympathisch" },
                { word: "Kuddelmuddel", hint: "Chaos" },
                { word: "Torschlusspanik", hint: "Angst" }
            ],

            // ⭐ Stars & Promis
            celebrities: [
                { word: "Paparazzi", hint: "Fotografen" },
                { word: "Roter Teppich", hint: "Glamour" },
                { word: "Autogramm", hint: "Unterschrift" },
                { word: "Fanclub", hint: "Verehrung" },
                { word: "Skandal", hint: "Aufregung" },
                { word: "Comeback", hint: "Rückkehr" },
                { word: "Plattenvertrag", hint: "Musik" },
                { word: "Welttournee", hint: "Konzerte" },
                { word: "Box Office", hint: "Kino" },
                { word: "Casting", hint: "Auswahl" },
                { word: "Bodyguard", hint: "Schutz" },
                { word: "Privatsphäre", hint: "Geheim" },
                { word: "Charity", hint: "Spenden" },
                { word: "Shitstorm", hint: "Kritik" },
                { word: "Influencer", hint: "Einfluss" },
                { word: "Viral", hint: "Verbreitung" },
                { word: "Trending", hint: "Aktuell" },
                { word: "Shitstorm", hint: "Empörung" },
                { word: "Award Show", hint: "Preisverleihung" },
                { word: "Lifestyle", hint: "Lebensart" }
            ],

            // Legacy categories with more words
            food: [
                { word: "Sushi", hint: "Japanisch" },
                { word: "Croissant", hint: "Französisch" },
                { word: "Tacos", hint: "Mexikanisch" },
                { word: "Pasta", hint: "Al dente" },
                { word: "Curry", hint: "Scharf" },
                { word: "Döner", hint: "Türkisch" },
                { word: "Ramen", hint: "Nudeln" },
                { word: "Burger", hint: "Amerikanisch" },
                { word: "Spaghetti", hint: "Lang" },
                { word: "Popcorn", hint: "Knallt" },
                { word: "Wasabi", hint: "Brennt" },
                { word: "Mozzarella", hint: "Cremig" },
                { word: "Pizza", hint: "Italienisch" },
                { word: "Bratwurst", hint: "Deutsch" },
                { word: "Kimchi", hint: "Koreanisch" },
                { word: "Bolognese", hint: "Soße" },
                { word: "Tiramisu", hint: "Dessert" },
                { word: "Paella", hint: "Spanisch" },
                { word: "Guacamole", hint: "Avocado" },
                { word: "Baguette", hint: "Stange" },
                { word: "Churros", hint: "Süß" },
                { word: "Gazpacho", hint: "Kalt" },
                { word: "Maultaschen", hint: "Schwäbisch" },
                { word: "Schnitzel", hint: "Paniert" },
                { word: "Kaiserschmarren", hint: "Österreich" }
            ],
            
            objects: [
                { word: "Regenschirm", hint: "Schützt" },
                { word: "AirPods", hint: "Musik" },
                { word: "Skateboard", hint: "Rollt" },
                { word: "Fernbedienung", hint: "TV" },
                { word: "Sonnenbrille", hint: "Cool" },
                { word: "Rucksack", hint: "Trägt" },
                { word: "Wasserflasche", hint: "Durst" },
                { word: "Powerbank", hint: "Strom" },
                { word: "Laptop", hint: "Aufklappen" },
                { word: "Bluetooth-Box", hint: "Drahtlos" },
                { word: "Smartwatch", hint: "Handgelenk" },
                { word: "Gaming-Stuhl", hint: "Zocken" },
                { word: "Kamera", hint: "Aufnahme" },
                { word: "Schreibtisch", hint: "Arbeiten" },
                { word: "Kühlschrank", hint: "Abkühlen" },
                { word: "Hoodie", hint: "Kapuze" },
                { word: "Monitor", hint: "Bild" },
                { word: "Spiegel", hint: "Reflex" },
                { word: "Timer", hint: "Zeit" },
                { word: "Snackautomat", hint: "Klemmt" },
                { word: "Escape Room", hint: "Rätsel" },
                { word: "Smartphone", hint: "Immer dabei" },
                { word: "Kopfhörer", hint: "Privat hören" },
                { word: "Tablet", hint: "Touchscreen" },
                { word: "Drohne", hint: "Fliegt" }
            ]
        };

